Access control to data sources
Data Ingestion to Blob storage - ADF Pipeline (Batch Ingestion)

Filter Delta Data to Data Lake - Parquet format

To access SCCM - search Software Centre from start menu
Service Desk - Ivanti Dashboard

Service Catalogue - Ivanti Dashboard

RLG-DEV-CloudDataPlatform

https://royallondon-mkt-stage1.campaign.adobe.com/
Ramasamy.Baskar/Adobe2021

URL for ADO License - https://gtcit.visualstudio.com/RLG%20Azure%20Data


etlconfig-rlgdataplatform - Get access to this repository from Richard 

Speak to Callum to get access to Non-Prod storage accounts 
https://portal.azure.com/#@royallondon.onmicrosoft.com/resource/subscriptions/5d142fbf-a1e2-457c-91dc-bdff0675116c/resourceGroups/rlg-dev-cdp-uks-storage-rg/providers/Microsoft.Storage/storageAccounts/rlgcdpnonproduksdlkstr/overview

\\royallondongroup.com\shares\Group_BI\Adobe\TestData



Golden Record for Test Strategy diagram  - Joe 

ADF Details for Development:-

Azure Data Factory  - rlg-dev-cdp-uks-adf
Subscription - RLG-DEV-CloudDataPlatform (5d142fbf-a1e2-457c-91dc-bdff0675116c)
Resource Group - rlg-dev-cdp-uks-data-rg
Location - UK South
Storage account - rlgcdpnonproduksdlkstr
rlg-Dev-cdp-uks-sqlsrvr.database.windows.net
rlg-Dev-cdp-uks-sqldb02



CDP Test Environment Details
Azure Data Factory  - rlg-test-cdp-uks-adf-01
Subscription - RLG-DEV-CloudDataPlatform (5d142fbf-a1e2-457c-91dc-bdff0675116c)
Resource Group - rlg-test-cdp-uks-data-rg
Location - UK South
Azure SQL Server Name - rlg-test-cdp-uks-sqlsrvr.database.windows.net
Database Name - rlg-test-cdp-uks-sqldb02

